base:
  project: winequality-project
  random_state: 42
  target_col: quality

data_source:
  s3_bucket: mlops-wine-demo
  filename: winequality-white.csv

load_data:
  raw_dataset_path: data/raw

split_data:
  train_path: data/processed/train_wine_quality.csv
  test_path: data/processed/test_wine_quality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      #alpha: 0.88
      #l1_ratio: 0.89
      #alpha: 0.9
      #l1_ratio: 0.4
      alpha: 0.1
      l1_ratio: 0.01

model_dir: models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: models/model.joblib

mlflow_config:
  artifacts_dir: mlflow-artifacts
  experiment_name: ElasticNet regression
  run_name: mlops
  registered_model_name: ElasticNetWineModel
  remote_server_uri: http://ec2-18-234-217-20.compute-1.amazonaws.com:5000/