base:
  project: winequality-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_bucket: mlops-wine-demo
  filename: winequality-red.csv

load_data:
  raw_dataset_path: data/raw

split_data:
  train_path: data/processed/train_wine_quality.csv
  test_path: data/processed/test_wine_quality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89

model_dir: models