base:
  project: winequality-project
  random_state: 42
  target_col: quality

data_source:
  s3_bucket: mlops-wine-demo
  filename: winequality-white.csv

load_data:
  raw_dataset_path: data/raw

split_data:
  train_path: data/processed/train_wine_quality.csv
  test_path: data/processed/test_wine_quality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      #alpha: 0.88
      #l1_ratio: 0.89
      alpha: 0.9
      l1_ratio: 0.4

model_dir: models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: models/model.joblib